[project]
name = "lab-langflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "json-repair>=0.30.3",
    "langflow>=1.6.4",
]

[tool.uv]
index-url = "https://mirrors.ustc.edu.cn/pypi/simple"
